### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by paulnijssen** [mallocator/Elasticsearch-HBase-River#5]
Hello,

I would like to use your river plugin, and update it for Elasticsearch v1.0.1, but I can't find any licencing information. Could you include the software licence you're using for this project?

**Comment by mallocator** [comment]
Sure, I'll add a licence file, I'm just super busy currently, so for now know that it's going to be Apache 2.0 (like all my other projects). I hope with that you can go ahead and not wait on me.
