### ISSUE TITLE
 ./plugin.bat install file:/D:/ziliao/elasticsearch-jdbc-2.3.1.0-dist.zip

### ISSUE THREAD

**Issue by fanyoujian** [mallocator/Elasticsearch-HBase-River#6]
报错：
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
请问该怎么解决？

**Comment by mallocator** [comment]
Sorry, I can't do much with this. Also rivers have been deprecated for use with ES, so it's probably a good idea to migrate to some other solution.
